### ISSUE TITLE
Oculus Gear VR browser isn't supported

### ISSUE THREAD

**Issue by ghost** [googlevr/webvr-ui#10] opened 2017-06-30 10:37 UTC
Trying the WebVR-UI with AFrame 0.5, the "Enter VR" button doesn't respond as expected.

**Test URL:** https://treasure-scraper.glitch.me/

**Expected result:** When clicking on the "Enter VR" button while wearing the Gear VR headset in the WebVR Oculus browser, it should launch VR mode and the user should be surrounded by the scene

**Actual result:** clicking on the "Enter VR" button does nothing

**Comment by Artyom17** [comment] 2017-06-30 22:00
The issue is in AFrame 0.4.0 or 0.5.0 (which is used by webvr-ui): it doesn't support GearVR / Oculus Browser. They added support to AFrame 0.6.0. 
I've created two pull requests - one for 0.4.0 and another for 0.5.0 with the fix for the issue in the older versions of A-Frame, but not sure if those will be merged or not.  You may check them out.

But the proper fix for this issue to migrate to A-Frame 0.6.0 ASAP.

**Comment by Artyom17** [comment] 2017-06-30 22:35
You also may quickly try the fixed versions of 0.4.0 and 0.5.0 by using these links for <script> element (instead of the default aframe.io....):
https://artyom17.github.io/aframe/dist/aframe-v0.4.0-fixed.js
https://artyom17.github.io/aframe/dist/aframe-v0.5.0-fixed.js

**Comment by ghost** [comment] 2017-07-03 10:07
Perfect, good work! 
The Aframe team doesn't do patch uplifts for old versions (as stated here https://twitter.com/dmarcos/status/881637839288455168) but upgrading to v0.6 should fix this problem.
Issue can be closed I guess

**Comment by hapticdata** [comment] 2017-07-06 01:31
I believe there is an issue here and would like more information.

Are you referring to the Samsung Internet browser? Chrome? Or are you referring to the [Carmel Developer Preview](https://www.oculus.com/experiences/gear-vr/1290985657630933/)?

Did you only attempt to use the [a-frame example](https://googlevr.github.io/webvr-ui/examples/aframe.html)?

thanks

**Comment by ghost** [comment] 2017-07-07 10:09
It looks like the issue was related to internal AFrame functions. I tested your WebVR-UI with the AFrame example on Oculus browser (formerly known as Carmel).
It now works with AFrame 0.6 and your library
(Checked with Samsung VR browser and Oculus browser on https://glitch.com/edit/#!/treasure-scraper)

**Comment by HalfdanJ** [comment] 2017-07-13 14:25
Ah, we should update the example to the newest version of aframe.

**Comment by hapticdata** [comment] 2017-08-29 19:26
I've updated the example to `aframe@0.6.1` it now works in Gear VR.

**Closed as completed by hapticdata** 2017-08-29 19:26 UTC
Labels: bug
