### ISSUE TITLE
iOs 11 : Safari : Broken UI

### ISSUE THREAD

**Issue by devasur** [googlevr/webvr-ui#15] opened 2017-09-22 08:10 UTC
Apologies in advance for logging an issue with insufficient data.  We use webvr-ui at Walkinto (https://walkinto.in).  Just started hearing back from users that the VR UI is broken on iOS 11 / Safari

Apparently the Magic Window is not aligned correctly, there is some sort of zooming happening with which button to enter split screen is inaccessible.  I do not have device to troubleshoot.  Anyone who has, and is on iOS 11, could you please test one of this sample urls?

https://goo.gl/n2LfjE
https://goo.gl/saSfPA

**Comment by jsantell** [comment] 2017-09-22 23:17
What kind of device do you have? Did it work on the device before iOS11?

We just tested iOS11 on an iPhone 7s and it worked well. I have a hunch it sounds like something in the webvr-polyfill and not having device parameters for the device.

**Comment by devasur** [comment] 2017-09-27 11:44
Not having device parameters is a common enough problem.  I don't have a device to test.  One of our users took it upon himself to test on every device on an Apple Store (all running iOS11).  He mentioned the links I shared to be broken on all devices after upgrading to iOS11.  if same links I shared is working for you then it is a bit of mystery.

**Comment by HalfdanJ** [comment] 2017-11-15 18:17
Closing the issue since we cant reproduce, but feel free to open it again if you have more data.

**Closed as completed by HalfdanJ** 2017-11-15 18:17 UTC
